use_frameworks!

platform :ios, '8.0'

target 'MMTakeImage_Example' do
  
#  pod 'MMTakeImage', :git => 'https://github.com/hamewang/MMTakeImage.git',:branch => 'master'
  pod 'MMTakeImage', :path => '../'

  target 'MMTakeImage_Tests' do
    inherit! :search_paths


  end
end
